-- DEPRECADO — ver estrutura nova (D033).
--
-- Substituído por:
--   db/migration/V2__seed_empresas.sql
--
-- Fluxo atual: ver db/README.md e README.md na raiz do projeto.
-- Não execute este arquivo.
